services:
  - type: web
    name: streamline-backend
    env: node
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: PORT
        value: 4000
      - key: NODE_ENV
        value: production